image: maven:3.5.3-jdk-10

before_script: sudo apt-get update && sudo apt-get install openjfx -y

stages:
  - build

gradle-build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
  only:
    - master