image: openjdk:10-jdk

before_script:
  - apt-get update && apt-get install openjfx maven -y

stages:
  - build

gradle-build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
  only:
    - master