image: gradle:jdk10

stages:
  - build

gradle-build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install openjfx
  script:
    - gradle jar
  artifacts:
    paths:
      - target/*.jar
  only:
    - master