image: gradle:jdk10

stages:
  - build

gradle-build:
  stage: build
  script:
      - sudo apt-get update
      - sudo apt-get install openjfx
  artifacts:
    paths:
      - target/*.jar
  only:
    - master